#!/usr/bin/env bash

err=0
output_msg=""
tmux_status=""

domains=("www.youtube.com" "youtube.com" "www.twitch.tv" "gql.twitch.tv" "x.com" "yletv.akamaized.net")

case "$1" in
    on)
        for dom in "${domains[@]}"; do
            sudo hostess add "$dom" 127.0.0.1 2>/dev/null || err=1
        done

        tmux_status="WORK"
        output_msg="work mode enabled"
        ;;
    off)
        for dom in "${domains[@]}"; do
            sudo hostess rm "$dom" 2>/dev/null || err=1
        done

        tmux_status="LAZY"
        output_msg="work mode disabled"
        ;;
    *)
        echo "[?] usage: workmode [on|off]"
        exit 1
        ;;
esac

if [[ $err -eq 0 ]]; then
    tmux set -g status-left " $tmux_status "
    echo "[+] $output_msg"
else 
    echo "[!] failed changing work mode"
    exit 1
fi

