#!/usr/bin/env bash

# docs: curl wttr.in/:help

OPTS="?2q"

if [[ "$#" -ne 1 ]]; then
    curl -s "wttr.in/helsinki$OPTS" # iata code default
else
    # preferably use iata codes instead of raw location names
    curl "wttr.in/$1$OPTS"
fi

